export const ui = {
  navSearch: 'Поиск',
  navUpload: 'Загрузка',
  navLogout: 'Выход',
  loginTitle: 'Вход в систему',
  loginSubtitle: 'Введите email и пароль для доступа к карте знаний',
  loginHeroTitle: 'Карта знаний R&D',
  loginHeroSubtitle: 'Поиск и синтез по корпоративным исследованиям',
  loginEmail: 'Email',
  loginPassword: 'Пароль',
  loginSubmit: 'Войти',
  searchPlaceholder: 'Запрос',
  searchSubmit: 'Найти',
  emptyResults: 'Нет результатов',
  resultsSources: 'Источники',
  resultsContradictions: 'Расхождения',
  sourceOpen: 'Открыть',
  confidence: 'Достоверность',
  performanceTotal: 'Время мс',
  statusProcessing: 'Обработка',
  statusDone: 'Готово',
  statusFailed: 'Ошибка',
  retry: 'Повтор',
  fieldRequired: 'Обязательное поле',
  mlProviderCloud: 'Yandex API',
  mlProviderLocal: 'Ollama',
  mlProviderToggle: 'Переключить Yandex API или Ollama',
  authCallbackProcessing: 'Авторизация',
  uploadTitle: 'Загрузка',
  uploadAction: 'Выбрать файл',
  uploadSubmit: 'Загрузить',
  uploadVisibility: 'Доступ',
  uploadUnsupportedFormat: 'Неподдерживаемый формат',
  visibilityPublic: 'Открытый',
  visibilityInternal: 'Внутренний',
  visibilityConfidential: 'Конфиденциальный',
  documentsTitle: 'Документы',
  documentName: 'Название',
  documentStatus: 'Статус',
  documentCreated: 'Загружен',
  documentDownload: 'Скачать',
  documentNotFound: 'Документ не найден',
  documentLoadFailed: 'Не удалось открыть файл',
  documentPreviewUnavailable: 'Предпросмотр недоступен, используйте скачивание',
  emptyDocuments: 'Нет документов',
} as const;
