export const ui = {
  appBrand: 'Nornickel AI Lab',
  navSearch: 'Поиск',
  navUpload: 'Загрузка',
  navDocuments: 'Документы',
  navLogout: 'Выход',
  navThemeLight: 'Светлая тема',
  navThemeDark: 'Тёмная тема',
  loginTitle: 'Вход',
  loginEmail: 'Email',
  loginPassword: 'Пароль',
  loginSubmit: 'Войти',
  searchTitle: 'Поиск по знаниям',
  searchPlaceholder: 'Запрос',
  searchSubmit: 'Найти',
  filterTitle: 'Фильтры',
  filterGeo: 'География',
  filterGeoRu: 'Россия',
  filterGeoForeign: 'Зарубеж',
  filterGeoWorld: 'Мир',
  filterYearFrom: 'Год от',
  filterYearTo: 'Год до',
  yearPickerPlaceholder: 'Выберите год',
  yearPickerClear: 'Сбросить',
  filterReset: 'Сбросить',
  queryConstructorOpen: 'Конструктор',
  queryConstructorTitle: 'Конструктор запроса',
  queryConstructorDescription: 'Материал, процесс, условия, география и период',
  queryConstructorMaterial: 'Материал',
  queryConstructorProcess: 'Процесс',
  queryConstructorConditions: 'Условия',
  queryConstructorPeriod: 'Период',
  queryConstructorMaterialPlaceholder: 'никель, медь, сульфаты',
  queryConstructorProcessPlaceholder: 'электроэкстракция, флотация',
  queryConstructorConditionsPlaceholder: 'сульфаты ≤300 мг/л, температура 25 °C',
  queryConstructorQuestion: 'Какие технические решения и подтверждённые данные описаны в источниках по указанным параметрам',
  queryConstructorApply: 'Вставить в запрос',
  queryConstructorCancel: 'Отмена',
  emptyResults: 'Нет результатов',
  emptySources: 'Источники не найдены',
  sourcesRequired: 'Источники обязательны при высокой достоверности',
  resultsSources: 'Источники',
  resultsContradictions: 'Расхождения',
  sourceOpen: 'Открыть',
  confidence: 'Достоверность',
  performanceTotal: 'Всего мс',
  performanceSearch: 'Поиск мс',
  performanceLlm: 'LLM мс',
  providerLabel: 'Провайдер',
  statusProcessing: 'Обработка',
  statusDone: 'Готово',
  statusFailed: 'Ошибка',
  retry: 'Повтор',
  fieldRequired: 'Обязательное поле',
  mlProviderGigachat: 'GigaChat API',
  mlProviderLocal: 'Ollama',
  mlProviderToggle: 'Переключить GigaChat API или Ollama',
  mlBulkSeed: 'Загрузить материалы',
  mlBulkReindex: 'Переиндексировать',
  mlBulkStarted: 'Запущено',
  mlBulkFailed: 'Не удалось запустить',
  mlBulkHintLocal: 'Локальный embed без GigaChat',
  authCallbackProcessing: 'Авторизация',
  uploadTitle: 'Загрузка документов',
  uploadAction: 'Выбрать файл',
  uploadSubmit: 'Загрузить',
  uploadUnsupportedFormat: 'Неподдерживаемый формат',
  uploadTooLarge: 'Файл слишком большой, максимум 200 МБ',
  uploadSuccess: 'Файл принят в обработку',
  documentsTitle: 'Документы',
  documentName: 'Название',
  documentStatus: 'Статус',
  documentCreated: 'Загружен',
  documentDownload: 'Скачать',
  documentTitle: 'Документ',
  documentNotFound: 'Документ не найден',
  documentLoadFailed: 'Не удалось открыть файл',
  documentPreviewUnavailable: 'Предпросмотр недоступен, используйте скачивание',
  emptyDocuments: 'Нет документов',
  documentsSearchPlaceholder: 'Название',
  documentsSearchEmpty: 'Нет результатов',
  navGraph: 'Граф',
  graphTitle: 'Граф знаний',
  graphEmpty: 'Граф пуст',
  graphLoadFailed: 'Не удалось загрузить граф',
  graphLegendLink: 'Связь',
  graphLegendContradiction: 'Расхождение',
  graphContradictionsTitle: 'Расхождения',
  graphContradictionsEmpty: 'Расхождений нет',
  graphContradictionFocus: 'Показать на графе',
} as const;
