export const ui = {
  appBrand: 'Nornickel AI Lab',
  navSearch: 'Поиск',
  navUpload: 'Загрузка',
  navDocuments: 'Документы',
  navLogout: 'Выход',
  navThemeLight: 'Светлая тема',
  navThemeDark: 'Тёмная тема',
  loginTitle: 'Вход',
  loginEmail: 'Email',
  loginPassword: 'Пароль',
  loginSubmit: 'Войти',
  searchTitle: 'Поиск по знаниям',
  searchPlaceholder: 'Запрос',
  searchSubmit: 'Найти',
  filterTitle: 'Фильтры',
  filterGeo: 'География',
  filterGeoRu: 'Россия',
  filterGeoForeign: 'Зарубеж',
  filterGeoWorld: 'Мир',
  filterYearFrom: 'Год от',
  filterYearTo: 'Год до',
  yearInvalid: 'Укажите целое число',
  yearMin: 'Год не раньше 1990',
  yearMax: 'Год не позже текущего',
  yearRangeInvalid: 'Год от не может быть больше года до',
  filterReset: 'Сбросить',
  filterOpen: 'Фильтры',
  filterClose: 'Закрыть',
  filterApply: 'Готово',
  queryConstructorDescription: 'Материал, процесс, условия, география и период',
  queryConstructorMaterial: 'Материал',
  queryConstructorProcess: 'Процесс',
  queryConstructorConditions: 'Условия',
  queryConstructorPeriod: 'Период',
  queryConstructorMaterialPlaceholder: 'никель, медь, сульфаты',
  queryConstructorProcessPlaceholder: 'электроэкстракция, флотация',
  queryConstructorConditionsPlaceholder: 'сульфаты ≤300 мг/л, температура 25 °C',
  queryConstructorQuestion: 'Какие технические решения и подтверждённые данные описаны в источниках по указанным параметрам',
  emptyResults: 'Нет результатов',
  emptySources: 'Источники не найдены',
  sourcesRequired: 'Источники обязательны при высокой достоверности',
  resultsSources: 'Источники',
  resultsContradictions: 'Расхождения',
  sourceOpen: 'Открыть',
  confidence: 'Достоверность',
  performanceTotal: 'Всего мс',
  performanceSearch: 'Индекс мс',
  performanceEmbed: 'Embed мс',
  performanceLlm: 'GigaChat мс',
  statusProcessing: 'Обработка',
  statusDone: 'Готово',
  statusFailed: 'Ошибка',
  retry: 'Повтор',
  fieldRequired: 'Обязательное поле',
  mlProviderGigachat: 'через API',
  mlProviderLocal: 'локально',
  mlProviderToggle: 'Переключить локально или через API',
  authCallbackProcessing: 'Авторизация',
  uploadTitle: 'Загрузка документов',
  uploadDescription: 'Файл, архив ZIP или папка с PDF и DOCX',
  uploadFormatsHint: 'Файл: PDF · DOCX · ZIP · Папка: PDF · DOCX (вложенные каталоги поддерживаются)',
  uploadAction: 'Выбрать файл',
  uploadDirectoryAction: 'Выбрать папку',
  uploadDirectoryEmpty: 'В папке нет PDF или DOCX',
  uploadDirectorySelected: '{count} файлов, напр. {sample}',
  uploadSubmit: 'Загрузить',
  uploadUnsupportedFormat: 'Неподдерживаемый формат',
  uploadTooLarge: 'Файл слишком большой, максимум 200 МБ',
  uploadSuccess: 'Файл принят в обработку',
  uploadBatchSuccess: 'Поставлено в очередь',
  documentsTitle: 'Документы',
  documentName: 'Название',
  documentStatus: 'Статус',
  documentCreated: 'Загружен',
  documentDownload: 'Скачать',
  documentTitle: 'Документ',
  documentNotFound: 'Документ не найден',
  documentLoadFailed: 'Не удалось открыть файл',
  documentPreviewUnavailable: 'Предпросмотр недоступен, используйте скачивание',
  emptyDocuments: 'Нет документов',
  documentsSearchPlaceholder: 'Название',
  documentsSearchEmpty: 'Нет результатов',
  navGraph: 'Граф',
  graphTitle: 'Граф знаний',
  graphEmpty: 'Граф пуст',
  graphLoadFailed: 'Не удалось загрузить граф',
  graphLegendLink: 'Связь',
  graphLegendContradiction: 'Расхождение',
  graphLegendEntity: 'Сущность (точка)',
  graphLegendDocument: 'Документ',
  graphContradictionsTitle: 'Расхождения',
  graphContradictionsEmpty: 'Расхождений нет',
  graphContradictionFocus: 'Показать на графе',
  answerGroups: 'Группы источников',
  answerGaps: 'Пробелы в знаниях',
  answerRecommendations: 'Рекомендации',
  answerExperts: 'Эксперты',
  answerFacilities: 'Площадки',
  answerExportMarkdown: 'Экспорт Markdown',
  sourcePage: 'стр.',
  sourceLookAt: 'Искать в документе:',
  sourceOpenAtPage: 'Открыть на странице',
  navDashboard: 'Дашборд',
  dashboardTitle: 'Аналитика знаний',
  dashboardDescription: 'Покрытие корпуса, активность запросов и зоны риска',
  dashboardDocuments: 'Документы (готово)',
  dashboardQueries: 'Запросы',
  dashboardGlossary: 'Термины глоссария',
  dashboardContradictions: 'Расхождения в графе',
  dashboardCoverageGeo: 'Покрытие по географии',
  dashboardGraphNodes: 'Узлы графа знаний',
  dashboardEmptyGeo: 'Нет данных по географии',
  dashboardLoadFailed: 'Не удалось загрузить аналитику',
  dashboardRefresh: 'Обновить',
  dashboardDocumentsProcessing: 'В обработке',
  geoCodeLabels: {
    RU: 'Россия',
    foreign: 'Зарубеж',
    world: 'Мир',
  },
  countryLabels: {
    Germany: 'Германия',
    Chile: 'Чили',
    Canada: 'Канада',
    Japan: 'Япония',
    USA: 'США',
  },
  graphNodeLabels: {
    Publication: 'Документ',
    Process: 'Процесс',
    Material: 'Материал',
    Conclusion: 'Вывод',
    Facility: 'Площадка',
    Experiment: 'Эксперимент',
    Expert: 'Эксперт',
    Property: 'Свойство',
    Equipment: 'Оборудование',
  },
} as const;
